name: seaice_tgrs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2
  - xarray
  - pandas
  - netcdf4
  - h5netcdf
  - cftime
  - scipy
  - matplotlib
  - requests
  - tqdm
  - pip
  - pip:
      - cdsapi
